# Generated by Django 5.2.9 on 2026-04-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_facility_options_remove_facility_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocluster',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
