# Generated by Django 5.2.9 on 2026-07-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_geoclusters_code_max4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='code',
            new_name='sac',
        ),
        migrations.AddField(
            model_name='office',
            name='vehicle_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
