# Generated by Django 5.2.9 on 2026-07-06 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_code_office_sac_office_vehicle_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSwapLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sac_a', models.CharField(max_length=50)),
                ('sac_b', models.CharField(max_length=50)),
                ('old_vehicle_code_a', models.CharField(blank=True, max_length=50, null=True)),
                ('old_vehicle_code_b', models.CharField(blank=True, max_length=50, null=True)),
                ('new_vehicle_code_a', models.CharField(blank=True, max_length=50, null=True)),
                ('new_vehicle_code_b', models.CharField(blank=True, max_length=50, null=True)),
                ('crew_swapped', models.BooleanField(default=True)),
                ('triggered_by', models.CharField(default='SYSTEM', max_length=100)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('office_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_logs_a', to='core.office')),
                ('office_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_logs_b', to='core.office')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
