# Generated by Django 5.2.9 on 2026-07-08 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_positiontype_shift_position_position_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionShiftRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_rosters', to='core.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_rosters', to='core.position')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_rosters', to='core.shift')),
            ],
            options={
                'ordering': ['date', 'position', 'shift'],
                'unique_together': {('position', 'shift', 'date')},
            },
        ),
    ]
