# Generated by Django 5.2.9 on 2026-07-08 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_positionshiftroster'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionScreenPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_permissions', to='core.position')),
                ('task_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.taskurl')),
            ],
            options={
                'unique_together': {('position', 'task_url')},
            },
        ),
    ]
