# Generated by Django 5.2.9 on 2026-07-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_positionscreenpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
