# Generated by Django 5.2.9 on 2026-07-09 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_office_vehicle_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleswaplog',
            name='new_vehicle_no_a',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicleswaplog',
            name='new_vehicle_no_b',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicleswaplog',
            name='old_vehicle_no_a',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicleswaplog',
            name='old_vehicle_no_b',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='VehicleSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_vehicle_code', models.CharField(blank=True, max_length=50, null=True)),
                ('from_vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('to_vehicle_code', models.CharField(blank=True, max_length=50, null=True)),
                ('to_vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('swap_crew', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_actioned', to=settings.AUTH_USER_MODEL)),
                ('from_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_from', to='core.office')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to='core.employee')),
                ('to_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_to', to='core.office')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
