# Generated by Django 5.2.9 on 2026-07-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_apikey_webhook_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='additional_roles',
            field=models.ManyToManyField(blank=True, related_name='additional_positions', to='core.role'),
        ),
    ]
