# Generated by Django 5.2.9 on 2026-07-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_position_additional_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionshiftroster',
            name='actual_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='positionshiftroster',
            name='actual_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='positionshiftroster',
            name='attendance_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('LEFT_EARLY', 'Left Early'), ('PARTIAL_SHIFT', 'Partial Shift'), ('WEEK_OFF', 'Week Off')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='positionshiftroster',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='positionshiftroster',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
