# Generated by Django 5.2.9 on 2026-07-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_positionshiftroster_actual_end_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='positionshiftroster',
            unique_together={('position', 'shift', 'date', 'employee')},
        ),
    ]
