# Generated by Django 5.2.9 on 2026-07-16 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_positionshiftroster_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('request_type', models.CharField(choices=[('ALLOCATION', 'New Shift Assignment'), ('SHIFT_CHANGE', 'Shift Transfer'), ('SWAP', 'Shift Swap / Cover'), ('REPLACEMENT', 'Early-Leave Replacement')], default='ALLOCATION', max_length=20)),
                ('status', models.CharField(choices=[('PENDING_CONSENT', 'Pending Employee Consent'), ('PENDING_APPROVAL', 'Pending Manager Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_CONSENT', max_length=20)),
                ('employee_consent', models.CharField(choices=[('PENDING', 'Pending Decision'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests_received', to='core.employee')),
                ('from_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_from', to='core.shift')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.position')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests_made', to='core.employee')),
                ('to_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_to', to='core.shift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
