# Generated by Django 5.2.9 on 2026-07-16 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_shiftchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiontype',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_types', to='core.project'),
        ),
        migrations.AddField(
            model_name='positiontype',
            name='shifts',
            field=models.ManyToManyField(blank=True, related_name='position_types', to='core.shift'),
        ),
        migrations.AddField(
            model_name='project',
            name='has_segments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='facility_type',
            field=models.CharField(blank=True, choices=[('PERMANENT', 'Permanent'), ('MOBILE', 'Mobile'), ('CAMP', 'Camp')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_groups', to='core.project'),
        ),
        migrations.AddField(
            model_name='shift',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='core.project'),
        ),
        migrations.AlterField(
            model_name='positiontype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='RoleSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='core.role')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('role_group', 'name')},
            },
        ),
        migrations.AddField(
            model_name='position',
            name='role_sub_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='core.rolesubgroup'),
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='positiontype',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_types', to='core.segment'),
        ),
        migrations.AddField(
            model_name='role',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_groups', to='core.segment'),
        ),
        migrations.AddField(
            model_name='shift',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='core.segment'),
        ),
        migrations.AlterUniqueTogether(
            name='positiontype',
            unique_together={('project', 'segment', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('project', 'segment', 'name')},
        ),
    ]
