# Generated by Django 5.2.9 on 2026-07-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_positiontype_project_positiontype_shifts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_type',
            field=models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Mobile', 'Mobile'), ('Camp', 'Camp')], max_length=50, null=True),
        ),
    ]
