# Generated by Django 5.2.9 on 2026-08-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_office_office_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='additional_jobs',
            field=models.ManyToManyField(blank=True, related_name='additional_positions_jb', to='core.job'),
        ),
        migrations.AddField(
            model_name='position',
            name='additional_sub_groups',
            field=models.ManyToManyField(blank=True, related_name='additional_positions_sg', to='core.rolesubgroup'),
        ),
    ]
