# Generated by Django 5.2.9 on 2026-08-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_position_additional_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitymaster',
            name='position_types',
            field=models.ManyToManyField(blank=True, related_name='facility_masters', to='core.positiontype'),
        ),
        migrations.AlterField(
            model_name='facilitymaster',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='facility_masters_roles', to='core.role'),
        ),
    ]
