# Generated by Django 5.2.9 on 2026-08-06 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_facilitymaster_position_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiontype',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_types', to='core.job'),
        ),
        migrations.AddField(
            model_name='positiontype',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_types', to='core.role'),
        ),
    ]
