# Generated by Django 5.2.9 on 2026-08-07 09:10

from django.db import migrations, models

def populate_office_types(apps, schema_editor):
    OfficeType = apps.get_model('core', 'OfficeType')
    OfficeType.objects.get_or_create(name='Permanent', defaults={'code': 'PERM'})
    OfficeType.objects.get_or_create(name='Mobile', defaults={'code': 'MOBILE'})
    OfficeType.objects.get_or_create(name='Camp', defaults={'code': 'CAMP'})

def rollback_office_types(apps, schema_editor):
    OfficeType = apps.get_model('core', 'OfficeType')
    OfficeType.objects.filter(name__in=['Permanent', 'Mobile', 'Camp']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_positiontype_job_positiontype_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='office',
            name='office_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(populate_office_types, rollback_office_types),
    ]
