# Generated by Django 5.2.9 on 2026-08-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_officetype_alter_office_office_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(db_index=True, default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='position',
            name='status',
            field=models.CharField(db_index=True, default='Active', max_length=20),
        ),
    ]
