# Generated by Django 5.2.9 on 2026-08-18 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_employee_is_deleted_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityDeploymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='facilitymaster',
            name='mode',
        ),
        migrations.AddField(
            model_name='facilitymaster',
            name='deployment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_masters', to='core.facilitydeploymentmode'),
        ),
    ]
