# Generated by Django 5.2.9 on 2026-08-18 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_facilitydeploymentmode_remove_facilitymaster_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='facilitymaster',
            name='facility_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_masters', to='core.facilityclass'),
        ),
        migrations.CreateModel(
            name='FacilitySubClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_classes', to='core.facilityclass')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('facility_class', 'name')},
            },
        ),
        migrations.AddField(
            model_name='facilitymaster',
            name='facility_sub_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_masters', to='core.facilitysubclass'),
        ),
    ]
